### ISSUE TITLE
超话推送有异常

### ISSUE THREAD

**Issue by onlyzqy** [Lawaxi/ShitBoy#8]
超话新帖会一直重复推送

**Comment by Lawaxi** [comment]
真的吗？正常应该不会
你看看日志有报错信息吗

**Comment by onlyzqy** [comment]
日志倒是没有报错信息，就是每隔定时都会发送同样的超话帖子出来

**Comment by onlyzqy** [comment]
今天又出现了重复推送的情况，每次推送前日志中会有一下信息

2023-07-21 14:39:01 I/stdout: https://wx2.sinaimg.cn/mw690/0087s0rvly1hg2lje4xvaj37ah3n8e8l.jpg
2023-07-21 14:39:02 I/stdout: https://wx4.sinaimg.cn/mw690/0087s0rvly1hg2lj3fy41j31831fy182.jpg
2023-07-21 14:39:02 I/stdout: https://wx2.sinaimg.cn/mw690/0087s0rvly1hg2lj61pxhj31ww2li4qt.jpg
2023-07-21 14:39:02 I/stdout: https://wx2.sinaimg.cn/mw690/0087s0rvly1hg2lj5wj9xj31ww2li1l1.jpg
2023-07-21 14:39:02 I/stdout: https://wx4.sinaimg.cn/mw690/0087s0rvly1hg2lj6njaaj31ww2li7wl.jpg
2023-07-21 14:39:03 I/stdout: https://wx4.sinaimg.cn/mw690/0087s0rvly1hg2lj62lbjj31ww2lix6s.jpg
2023-07-21 14:39:06 W/stderr: cn.hutool.core.io.IORuntimeException: UnknownHostException: wx3jpg
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpRequest.send(HttpRequest.java:1328)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1176)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpRequest.execute(HttpRequest.java:1050)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpRequest.execute(HttpRequest.java:1026)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar//net.lawaxi.util.sender.WeiboSender.getRes(WeiboSender.java:251)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar//net.lawaxi.util.sender.WeiboSender.run(WeiboSender.java:105)
2023-07-21 14:39:06 W/stderr: Caused by: java.net.UnknownHostException: wx3jpg
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
2023-07-21 14:39:06 W/stderr: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
2023-07-21 14:39:06 W/stderr: 	at java.base/java.net.Socket.connect(Socket.java:633)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
2023-07-21 14:39:06 W/stderr: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpConnection.connect(HttpConnection.java:384)
2023-07-21 14:39:06 W/stderr: 	at shitboy-0.1.10-test3.mirai2.jar[shared]//cn.hutool.http.HttpRequest.send(HttpRequest.java:1323)
2023-07-21 14:39:06 W/stderr: 	... 5 more

**Comment by Lawaxi** [comment]
试试0.1.10-test4

**Comment by onlyzqy** [comment]
0.1.10-test5，还是有这个情况，日志如下

2023-07-24 14:39:03 I/stdout: https://wx2.sinaimg.cn/mw690/4c2b9adbly1hg7wglay5lg208c0ethdw.gif\
2023-07-24 14:39:03 W/stderr: java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@790cd0c, considering use gif/png/bmp/jpg format. image header: 62 61 64 20 72 65 71 75 65 73 74 21 0A
2023-07-24 14:39:03 W/stderr: 	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
2023-07-24 14:39:03 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2023-07-24 14:39:03 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-07-24 14:39:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-24 14:39:06 V/Bot.3107059336: Group(746438576) <- 【林佳怡超话新内容：回復生命值】
▼林佳怡超话小林的翻牌怎么关掉了呀，有说什么时候可以发吗😭​​​​

link: https://weibo.com/6668928043/Nblmw1uUe
2023-07-24 14:39:15 E/ExternalResourceLeakObserver: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@4515eaea). Add jvm option `-Dmirai.resource.creation.stack.enabled=true` to show creation stack track
2023-07-24 14:39:15 E/ExternalResourceLeakObserver: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@7914d476). Add jvm option `-Dmirai.resource.creation.stack.enabled=true` to show creation stack track
2023-07-24 14:40:03 I/stdout: https://wx2.sinaimg.cn/mw690/4c2b9adbly1hg7wglay5lg208c0ethdw.gif\
2023-07-24 14:40:03 W/stderr: java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@7261f01e, considering use gif/png/bmp/jpg format. image header: 62 61 64 20 72 65 71 75 65 73 74 21 0A
2023-07-24 14:40:03 W/stderr: 	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
2023-07-24 14:40:03 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2023-07-24 14:40:03 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-07-24 14:40:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-24 14:40:05 V/Bot.3107059336: Group(746438576) <- 【林佳怡超话新内容：回復生命值】
▼林佳怡超话小林的翻牌怎么关掉了呀，有说什么时候可以发吗😭​​​​

link: https://weibo.com/6668928043/Nblmw1uUe
2023-07-24 14:40:15 E/ExternalResourceLeakObserver: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@6150dac2). Add jvm option `-Dmirai.resource.creation.stack.enabled=true` to show creation stack track
2023-07-24 14:41:02 I/stdout: https://wx2.sinaimg.cn/mw690/4c2b9adbly1hg7wglay5lg208c0ethdw.gif\
2023-07-24 14:41:03 W/stderr: java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@5e549db1, considering use gif/png/bmp/jpg format. image header: 62 61 64 20 72 65 71 75 65 73 74 21 0A
2023-07-24 14:41:03 W/stderr: 	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
2023-07-24 14:41:03 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2023-07-24 14:41:03 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-07-24 14:41:03 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-24 14:41:06 V/Bot.3107059336: Group(746438576) <- 【林佳怡超话新内容：回復生命值】
▼林佳怡超话小林的翻牌怎么关掉了呀，有说什么时候可以发吗😭​​​​

link: https://weibo.com/6668928043/Nblmw1uUe

**Comment by Lawaxi** [comment]
已更新
因为超话关注我本身需要不大，一直没测试，不好意思，也感谢您一直反馈问题

**Comment by onlyzqy** [comment]
反馈一些使用中出现的异常，感谢您不断的进行修正。
0.1.10-test6版本目前情况是这样的，我一共有关注四个超话，但仅有一个超话存在重复推送的情况。
此版本会重复推送近期多条超话发帖，目前我遇到的会重复推送两条，日志如下

2023-07-27 21:40:03 I/stdout: https://wx1.sinaimg.cn/mw690/008hqX05gy1hgbrwxfmt0j30u0blj1l1.jpg
2023-07-27 21:40:04 I/stdout: https://wx2.sinaimg.cn/mw690/008hqX05gy1hgbrqicvylj30u06mdx6q.jpg
2023-07-27 21:40:04 W/stderr: cn.hutool.core.io.IORuntimeException: UnknownHostException: https%3A%2F%2Fwx4.sinaimg.cn%2Forj480%2F0088A71wly1hg9ogd3vtdj30u0140qii.jpg&
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpRequest.send(HttpRequest.java:1328)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1176)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpRequest.execute(HttpRequest.java:1050)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpRequest.execute(HttpRequest.java:1026)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar//net.lawaxi.util.sender.WeiboSender.getRes(WeiboSender.java:262)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar//net.lawaxi.util.sender.WeiboSender.run(WeiboSender.java:99)
2023-07-27 21:40:04 W/stderr: Caused by: java.net.UnknownHostException: https%3A%2F%2Fwx4.sinaimg.cn%2Forj480%2F0088A71wly1hg9ogd3vtdj30u0140qii.jpg&
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
2023-07-27 21:40:04 W/stderr: 	at java.base/java.net.Socket.connect(Socket.java:633)
2023-07-27 21:40:04 W/stderr: 	at java.base/java.net.Socket.connect(Socket.java:583)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
2023-07-27 21:40:04 W/stderr: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpConnection.connect(HttpConnection.java:384)
2023-07-27 21:40:04 W/stderr: 	at shitboy-0.1.10-test6.mirai2.jar[shared]//cn.hutool.http.HttpRequest.send(HttpRequest.java:1323)
2023-07-27 21:40:04 W/stderr: 	... 5 more

**Comment by Lawaxi** [comment]
已更新
